[tool.poetry]
name = "pudzu-pillar"
version = "0.9.2"
description = "Various imaging utilities, monkey-patched onto Pillow"
packages = [{ include = "pudzu" }]
keywords = ["pudzu", "imaging", "pillow"]

authors = ["Uri Granta <uri.granta+python@gmail.com>"]
homepage = "https://github.com/Udzu/pudzu-packages/pudzu-pillar/"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7"
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.16.0"
Pillow = "^6.0.0"
pudzu-utils = "^0.9.2"
requests = { version = "^2.22.0", optional = true }
scipy = { version = "^1.3.1", optional = true }
pyphen = { version = "^0.10.0", optional = true }
python-bidi = { version = "^0.4.2", optional = true }
arabic-reshaper = { version = "^2.0.15", optional = true }

[tool.poetry.dev-dependencies]
mypy = "*"
pylint = "*"
black = { version = "*", allow-prereleases = true }
isort = "*"
taskipy = "*"
pudzu-utils = { path = "../pudzu-utils", develop = true }
pytest = "*"
pytest-mypy = "*"
pytest-pylint = "*"

[tool.poetry.extras]
image_extras = ["scipy", "requests"]
text_extras = ["pyphen", "python-bidi", "arabic-reshaper"]

[tool.taskipy.tasks]
tests = "pytest --pylint --mypy"
format = "task isort && task black"
mypy = "pytest --mypy -m mypy"
pylint = "pytest --pylint -m pylint"
black = "black ."
isort = "isort ."

[tool.black]
line-length = 100
target-version = ['py37']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
line_length = 100

[tool.pylint.'MESSAGES CONTROL']
disable = "all"
enable = [
    "abstract-class-instantiated",
    "abstract-method",
    "access-member-before-definition",
    "anomalous-backslash-in-string",
    "anomalous-unicode-escape-in-string",
    "arguments-differ",
    "assert-on-tuple",
    "assign-to-new-keyword",
    "assigning-non-slot",
    "assignment-from-no-return",
    "assignment-from-none",
    "attribute-defined-outside-init",
    "bad-except-order",
    "bad-exception-context",
    "bad-format-character",
    "bad-format-string",
    "bad-format-string-key",
    "bad-indentation",
    "bad-mcs-classmethod-argument",
    "bad-mcs-method-argument",
    "bad-open-mode",
    "bad-option-value",
    "bad-reversed-sequence",
    "bad-staticmethod-argument",
    "bad-str-strip-call",
    "bad-super-call",
    "binary-op-exception",
    "blacklisted-name",
    "catching-non-exception",
    "cell-var-from-loop",
    "continue-in-finally",
    "dangerous-default-value",
    "differing-param-doc",
    "differing-type-doc",
    "duplicate-argument-name",
    "duplicate-bases",
    "duplicate-except",
    "duplicate-key",
    "empty-docstring",
    "expression-not-assigned",
    "fatal",
    "format-needs-mapping",
    "function-redefined",
    "global-at-module-level",
    "global-variable-not-assigned",
    "global-variable-undefined",
    "import-self",
    "inconsistent-mro",
    "inherit-non-class",
    "init-is-generator",
    "invalid-all-object",
    "invalid-format-index",
    "invalid-length-returned",
    "invalid-metaclass",
    "invalid-sequence-index",
    "invalid-slice-index",
    "invalid-slots",
    "invalid-slots-object",
    "invalid-star-assignment-target",
    "len-as-condition",
    "line-too-long",
    "literal-comparison",
    "logging-format-interpolation",
    "logging-format-truncated",
    "logging-not-lazy",
    "logging-too-few-args",
    "logging-too-many-args",
    "logging-unsupported-format",
    "lost-exception",
    "method-hidden",
    "misplaced-bare-raise",
    "misplaced-future",
    "missing-final-newline",
    "missing-format-argument-key",
    "missing-format-attribute",
    "missing-format-string-key",
    "missing-kwoa",
    "mixed-format-string",
    "mixed-indentation",
    "mixed-line-endings",
    "multiple-statements",
    "no-method-argument",
    "no-name-in-module",
    "no-self-argument",
    "no-value-for-parameter",
    "non-iterator-returned",
    "non-parent-init-called",
    "nonexistent-operator",
    "nonlocal-and-global",
    "nonlocal-without-binding",
    "not-a-mapping",
    "not-an-iterable",
    "not-async-context-manager",
    "not-callable",
    "not-in-loop",
    "notimplemented-raised",
    "pointless-statement",
    "pointless-string-statement",
    "raising-bad-type",
    "raising-non-exception",
    "redefine-in-handler",
    "redefined-argument-from-local",
    "redundant-keyword-arg",
    "redundant-unittest-assert",
    "reimported",
    "relative-beyond-top-level",
    "repeated-keyword",
    "return-in-init",
    "return-outside-function",
    "signature-differs",
    "single-string-used-for-slots",
    "singleton-comparison",
    "star-needs-assignment-target",
    "super-init-not-called",
    "syntax-error",
    "too-few-format-args",
    "too-many-format-args",
    "too-many-function-args",
    "too-many-star-expressions",
    "trailing-comma-tuple",
    "trailing-newlines",
    "trailing-whitespace",
    "truncated-format-string",
    "unable-to-import",
    "unbalanced-tuple-unpacking",
    "undefined-all-variable",
    "undefined-loop-variable",
    "undefined-variable",
    "unexpected-keyword-arg",
    "unexpected-special-method-signature",
    "unpacking-non-sequence",
    "unreachable",
    "unrecognized-inline-option",
    "unsupported-assignment-operation",
    "unsupported-binary-operation",
    "unsupported-delete-operation",
    "unsupported-membership-test",
    "unused-format-string-argument",
    "unused-import",
    "unused-variable",
    "used-before-assignment",
    "useless-else-on-loop",
    "useless-super-delegation",
    "using-constant-test",
    "yield-inside-async-function",
    "yield-outside-function"
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

